from urllib.parse import parse_qsl, parse_qs
import datetime
from linebot_import_api import *

def fruit_serch(event):
    message = TemplateSendMessage(
        alt_text='Buttons template',
        template=CarouselTemplate(
            columns=[
                CarouselColumn(
                    thumbnail_image_url='fruit1.jpg',
                    title='漿果類',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='草莓',
                            display_text='查詢草莓',
                            data='action=查詢草莓'
                        ),
                        PostbackAction(
                            label='奇異果',
                            display_text='查詢奇異果',
                            data='action=查詢奇異果'
                        ),
                        PostbackAction(
                            label='藍莓',
                            display_text='查詢藍莓',
                            data='action=查詢藍莓'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='fruit2.jpg',
                    title='瓜果類',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='沐浴乳',
                            display_text='想索取沐浴乳',
                            data='action=索取備品&item=沐浴乳'
                        ),
                        PostbackAction(
                            label='洗髮精',
                            display_text='想索取洗髮精',
                            data='action=索取備品&item=洗髮精'
                        ),
                        PostbackAction(
                            label='乳液',
                            display_text='想索取乳液',
                            data='action=索取備品&item=乳液'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='fruit3.jpg',
                    title='柑橘類',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='礦泉水',
                            display_text='想索取礦泉水',
                            data='action=索取備品&item=礦泉水'
                        ),
                        PostbackAction(
                            label='3合1沖泡咖啡包',
                            display_text='想索取3合1沖泡咖啡包',
                            data='action=索取備品&item=3合1沖泡咖啡包'
                        ),
                        PostbackAction(
                            label='紅茶茶包',
                            display_text='想索取紅茶茶包',
                            data='action=索取備品&item=紅茶茶包'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='fruit4.jpg',
                    title='梨果類',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='沐浴乳',
                            display_text='想索取沐浴乳',
                            data='action=索取備品&item=沐浴乳'
                        ),
                        PostbackAction(
                            label='洗髮精',
                            display_text='想索取洗髮精',
                            data='action=索取備品&item=洗髮精'
                        ),
                        PostbackAction(
                            label='乳液',
                            display_text='想索取乳液',
                            data='action=索取備品&item=乳液'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='fruit5.jpg',
                    title='核果類',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='沐浴乳',
                            display_text='想索取沐浴乳',
                            data='action=索取備品&item=沐浴乳'
                        ),
                        PostbackAction(
                            label='洗髮精',
                            display_text='想索取洗髮精',
                            data='action=索取備品&item=洗髮精'
                        ),
                        PostbackAction(
                            label='乳液',
                            display_text='想索取乳液',
                            data='action=索取備品&item=乳液'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='fruit6.jpg',
                    title='熱帶水果',
                    text='想要查詢哪個水果?',
                    actions=[
                        PostbackAction(
                            label='沐浴乳',
                            display_text='想索取沐浴乳',
                            data='action=索取備品&item=沐浴乳'
                        ),
                        PostbackAction(
                            label='洗髮精',
                            display_text='想索取洗髮精',
                            data='action=索取備品&item=洗髮精'
                        ),
                        PostbackAction(
                            label='乳液',
                            display_text='想索取乳液',
                            data='action=索取備品&item=乳液'
                        )
                    ]
                )
            ]
        )
    )
    line_bot_api.reply_message(event.reply_token, message)