from urllib.parse import parse_qsl, parse_qs
import datetime
from linebot_import_api import *

def fruit_serch(event):
    message = TemplateSendMessage(
        alt_text='搜尋',
        template=CarouselTemplate(
            columns=[
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit1.jpg?raw=true',
                    title='漿果類',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='草莓',
                            display_text='查詢草莓',
                            data='action=查詢草莓'
                        ),
                        PostbackAction(
                            label='奇異果',
                            display_text='查詢奇異果',
                            data='action=查詢奇異果'
                        ),
                        PostbackAction(
                            label='藍莓',
                            display_text='查詢藍莓',
                            data='action=查詢藍莓'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit2.jpg?raw=true',
                    title='瓜果類',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='西瓜',
                            display_text='查詢西瓜',
                            data='action=查詢西瓜'
                        ),
                        PostbackAction(
                            label='哈密瓜',
                            display_text='查詢哈密瓜',
                            data='action=查詢哈密瓜'
                        ),
                        PostbackAction(
                            label='木瓜',
                            display_text='查詢木瓜',
                            data='action=查詢木瓜'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit3.jpg?raw=true',
                    title='柑橘類',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='柳丁',
                            display_text='查詢柳丁',
                            data='action=查詢柳丁'
                        ),
                        PostbackAction(
                            label='檸檬',
                            display_text='查詢檸檬',
                            data='action=查詢檸檬'
                        ),
                        PostbackAction(
                            label='柚子',
                            display_text='查詢柚子',
                            data='action=查詢柚子'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit4.jpg?raw=true',
                    title='梨果類',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='蘋果',
                            display_text='查詢蘋果',
                            data='action=查詢蘋果'
                        ),
                        PostbackAction(
                            label='楊桃',
                            display_text='查詢楊桃',
                            data='action=查詢楊桃'
                        ),
                        PostbackAction(
                            label='梨子',
                            display_text='查詢梨子',
                            data='action=查詢梨子'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit5.jpg?raw=true',
                    title='核果類',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='水蜜桃',
                            display_text='查詢水蜜桃',
                            data='action=查詢水蜜桃'
                        ),
                        PostbackAction(
                            label='李子',
                            display_text='查詢李子',
                            data='action=查詢李子'
                        ),
                        PostbackAction(
                            label='櫻桃',
                            display_text='查詢櫻桃',
                            data='action=查詢櫻桃'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://github.com/briankuo123/AI_final_fruit_linebot/blob/main/fruit6.jpg?raw=true',
                    title='熱帶水果',
                    text='請選擇想查詢的水果',
                    actions=[
                        PostbackAction(
                            label='鳳梨',
                            display_text='查詢鳳梨',
                            data='action=查詢鳳梨'
                        ),
                        PostbackAction(
                            label='香蕉',
                            display_text='查詢香蕉',
                            data='action=查詢香蕉'
                        ),
                        PostbackAction(
                            label='蓮霧',
                            display_text='查詢蓮霧',
                            data='action=查詢蓮霧'
                        )
                    ]
                ),
            ]
        )
    )
    line_bot_api.reply_message(event.reply_token, message)
